[versions]
kotlinVersion = "1.9.21"

[libraries]
test-kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlinVersion" }
test-strikt = "io.strikt:strikt-core:0.34.1"
lokaliseApi = "com.ioki:lokalise-api:0.0.2"
kotlinCoroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }
dokka = "org.jetbrains.dokka:1.9.10"
