name: 'Gradle Wrapper Upgrade'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  upgrade-gradle-wrapper:
    runs-on: ubuntu-latest
    env:
      WRAPPER_UPGRADE_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upgrade Gradle Wrapper
        run: ./gradlew upgradeGradleWrapperLokaliseGradlePlugin