name: 'Publish Snapshot'

on:
  push:
    branches:
      - 'main'

env:
  SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish to Sonatype Snapshot
        run: ./gradlew publishAllPublicationsToSonatypeSnapshotRepository